server:
  port: 8091
spring:
  redis:
    #数据库索引
    database: 0
    host: 192.168.1.150
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  application:
    name: buyercloudfeign
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.150:8088/eureka

