server:
  port: 8091
spring:
  application:
    name: buyercloudfeign
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.116:8088/eureka